version: '3.8'
services:
    mysql:
        image: 'mysql:8.0.22'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: matcha
        volumes:
            - db_mysql:/var/lib/mysql
        ports:
            - 3306:3306
volumes:
    db_mysql:
networks:
    default:
        driver: bridge
