GET http://localhost:5000/posts
Authorization: Bearer eyJbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoid3BhcmsiLCJpYXQiOjE2MDkwNzk5OTl9.B1EIPClaDs_hautEECqX4fHWjg9TA_OGsH-1LcnIWdI

###

POST http://localhost:5000/auth/sign_in
Content-Type: application/json

{
	"username": "wpark"
}